name: forests-offsets-fire
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.10
  - fsspec
  - tqdm
  - click
  - beautifulsoup4 
  - pip
  - git 
  - geopandas
  - numpy
  - pandas
  - pyarrow
  - fuzzywuzzy
  - s3fs
  - prefect<2.0
  - jupyterhub-singleuser>=3.0,<4.0
  - pip:
    - carbonplan-styles
    - carbonplan-forest-offsets
    - censusgeocode

