name: forests-offsets-fire
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.10
  - awscli
  - beautifulsoup4
  - click
  - dask
  - fiona==1.9.4
  - fsspec
  - geopandas
  - git
  - jupyterhub-singleuser>=3.0,<4.0
  - mbutil
  - ndpyramid
  - nodejs
  - numpy
  - pandas
  - pip
  - pre-commit
  - prefect<2.0
  - pyarrow
  - pygmt
  - regionmask
  - s3fs
  - shapely
  - thefuzz
  - tippecanoe
  - tqdm
  - xarray==2023.01.0
  - xesmf
  - zarr
  - rioxarray
  - pip:
      - carbonplan-forest-offsets
      - carbonplan-styles
      - carbonplan-data
      - censusgeocode
      - skyplane[aws]
