name: FIRMS NRT

on:
  pull_request:

  push:
    branches:
      - main
  schedule:
    - cron: 0 6 * * * # 11 am PT  = 6 UTC
  workflow_dispatch:

jobs:
  flows:
    runs-on: ubuntu-latest

    env:
      FIRMS_MAP_KEY: ${{ secrets.FIRMS_MAP_KEY }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-west-2

    timeout-minutes: 5
    container:
      image: quay.io/carbonplan/forest-offsets-fires:latest
      options: --user root

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v3

      - uses: conda-incubator/setup-miniconda@v2
        with:
          # Specify python version your environment will have. Remember to quote this, or
          # YAML will think you want python 3.1 not 3.10
          python-version: '3.10'
          # This uses *miniforge*, rather than *minicond*. The primary difference is that
          # the defaults channel is not enabled at all
          miniforge-version: latest
          # These properties enable the use of mamba, which is much faster and far less error
          # prone than conda while being completely compatible with the conda CLI
          use-mamba: true
          mamba-version: '*'

      - name: Install some packages
        # The `-l` is needed so conda environment activation works correctly
        shell: bash -l {0}
        run: |
          mamba install -c conda-forge tippecanoe mbutil

      # - name: try tippacanoe
      #   shell: bash -l {0}
      #   run: |
      #     tippecanoe --help

      # - name: install tippacanoe
      #   run: |
      #     git clone https://github.com/mapbox/tippecanoe.git
      #     cd tippecanoe
      #     make -j
      #     make install

      # - name: install mbutil
      #   run: |
      #     git clone https://github.com/mapbox/mbutil.git
      #     cd mbutil
      #     ./mb-util -h
      #     sudo python setup.py install

      - name: run-script
        run: |
          # python carbonplan_forest_offsets_fires/scripts/firms_nrt_ETL.py
          python scripts/firms_nrt_ETL.py
